# This file is machine-generated - editing it directly is not advised

[[AsmMacro]]
git-tree-sha1 = "a3bd92d3cd222cd5cf9aa602ffe842faa909773a"
uuid = "f617cd02-e7fb-5dad-8d07-aa96542e7fbb"
version = "0.1.0"
