# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[OpenCL]]
deps = ["Libdl", "LinearAlgebra", "Printf"]
git-tree-sha1 = "95c0e41b075c6a326952044be29defa9c2ec1f02"
uuid = "08131aa3-fb12-5dee-8b74-c09406e224a2"
version = "0.8.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
