# This file is machine-generated - editing it directly is not advised

[[NamedTuples]]
git-tree-sha1 = "78c33ab43ef2aac9127d53edcb7a92e7fa63c126"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "5.0.0"
