# This file is machine-generated - editing it directly is not advised

[[ExprTools]]
git-tree-sha1 = "38fe9afc9bdf8708213ef9dcd5557da90ea6a2d5"
uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
version = "0.1.5"

[[RuntimeGeneratedFunctions]]
deps = ["ExprTools", "SHA", "Serialization"]
git-tree-sha1 = "e02f14dfe3a8d3b8fc92ca80c1882bfdbc015e07"
uuid = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
version = "0.5.1"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
