# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[OptimKit]]
deps = ["LinearAlgebra", "Printf"]
git-tree-sha1 = "24809c0f09f6faa46a1c9a91581017d175f899ca"
uuid = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
version = "0.3.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
