# This file is machine-generated - editing it directly is not advised

[[MIDI]]
git-tree-sha1 = "d48a59e8b1298fee39da0c5b01fab1379ca98251"
uuid = "f57c4921-e30c-5f49-b073-3f2f2ada663e"
version = "1.8.1"
