# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MLJModelInterface]]
deps = ["Random", "ScientificTypes", "StatisticalTraits"]
git-tree-sha1 = "96dedd0ca1b75624ff180b265257f3c168047cda"
uuid = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
version = "0.4.1"

[[PartialLeastSquaresRegressor]]
deps = ["LinearAlgebra", "MLJModelInterface", "Random", "Statistics"]
git-tree-sha1 = "542c9fa7cbb93fbff32b80483f9e44aed5c0751b"
uuid = "f4b1acfe-f311-436c-bb79-8483f53c17d5"
version = "2.1.0"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[ScientificTypes]]
git-tree-sha1 = "b4e89a674804025c4a5843e35e562910485690c2"
uuid = "321657f4-b219-11e9-178b-2701a2544e81"
version = "1.1.2"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StatisticalTraits]]
deps = ["ScientificTypes"]
git-tree-sha1 = "0daf443864a1fbb415d782c1dfd161d954140574"
uuid = "64bff920-2084-43da-a3e6-9bb72801c0c9"
version = "0.1.1"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
