# This file is machine-generated - editing it directly is not advised

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DocOpt]]
deps = ["Dates", "Printf"]
git-tree-sha1 = "866efe767d646ee8c66b15ff22520c03a1200ca7"
uuid = "968ba79b-81e4-546f-ab3a-2eecfa62a9db"
version = "0.4.2"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
