# This file is machine-generated - editing it directly is not advised

[[Fire]]
git-tree-sha1 = "4f1bc48edc2369ddd6e93a200390e0bc2a5c802d"
uuid = "652a1917-b8e5-5d9b-be38-bbf27e56fe44"
version = "0.1.1"
