# This file is machine-generated - editing it directly is not advised

[[ScientificTypes]]
git-tree-sha1 = "1d3f5f8bdf5dd0c9951eb9c595ee08a728aec331"
uuid = "321657f4-b219-11e9-178b-2701a2544e81"
version = "1.1.1"
