# This file is machine-generated - editing it directly is not advised

[[Julog]]
git-tree-sha1 = "99f56a184affb34df2d0198e66acf5ea8d0f75f8"
uuid = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
version = "0.1.9"
