# This file is machine-generated - editing it directly is not advised

[[KrylovKit]]
deps = ["LinearAlgebra", "Printf"]
git-tree-sha1 = "f66c3e1a5fb1433622dcefe4ffa09e11776a095c"
uuid = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
version = "0.5.2"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
