# This file is machine-generated - editing it directly is not advised

[[Tricks]]
git-tree-sha1 = "8280b6d0096e88b77a84f843fa18620d3b20e052"
uuid = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
version = "0.1.4"
