# This file is machine-generated - editing it directly is not advised

[[ConcreteStructs]]
git-tree-sha1 = "d3cb9f9cd86434a8d6f9d7e43280f6da46d2fea5"
uuid = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
version = "0.2.2"
