# This file is machine-generated - editing it directly is not advised

[[GeometricalPredicates]]
git-tree-sha1 = "04776c0dc233eafa617b1a52ca58db2338b08836"
uuid = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
version = "0.4.0"
