# This file is machine-generated - editing it directly is not advised

[[DBInterface]]
git-tree-sha1 = "441a377eb7f994cd454b7c45f29f911ce0d42ce0"
uuid = "a10d1c49-ce27-4219-8d33-6db1a4562965"
version = "2.4.0"
