# This file is machine-generated - editing it directly is not advised

[[ConfParser]]
git-tree-sha1 = "db2712392fbf7dd12eff7c2ea620a34b5d0ad7b9"
uuid = "88353bc9-fd38-507d-a820-d3b43837d6b9"
version = "0.1.2"
