# This file is machine-generated - editing it directly is not advised

[[GeoInterface]]
deps = ["RecipesBase"]
git-tree-sha1 = "62f6ed44e73c11d10e282053d70b33b0ed8dcbe2"
uuid = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
version = "0.5.4"

[[RecipesBase]]
git-tree-sha1 = "b3fb709f3c97bfc6e948be68beeecb55a0b340ae"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.1.1"
