# This file is machine-generated - editing it directly is not advised

[[ResultTypes]]
git-tree-sha1 = "b6322d2f7c92072a59c625d9ec359b39727bb6a7"
uuid = "08a2b407-ddc3-586a-afd6-c784ad1fffe2"
version = "3.1.0"
