# This file is machine-generated - editing it directly is not advised

[[JuliennedArrays]]
git-tree-sha1 = "5c5239dc913723f5e1357f584fd55caee808016d"
uuid = "5cadff95-7770-533d-a838-a1bf817ee6e0"
version = "0.2.2"
